name: Deploy Website to cPanel

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Auto-Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: 🟢 Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: 📦 Install FTP Client Library
      run: npm install basic-ftp

    - name: 📂 Run custom sequential upload
      run: node deploy.js
      env:
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
